### ISSUE TITLE
Signature of ``BitVec.shiftLeft, BitVec.ushiftRight, BitVec.sshiftRight, BitVec.zeroExtend`` does not match SMT-LIB

### ISSUE THREAD

**Issue by PratherConid** [leanprover/std4#302]
According to https://smtlib.cs.uiowa.edu/logics-all.shtml#QF_BV, the type of bitvec shift operations should be ``∀ {n : Nat}, BitVec n → BitVec n → BitVec n`` instead of ``∀ {n : Nat}, BitVec n → Nat → BitVec n``

**Comment by PratherConid** [comment]
Sounds good. I think for smt-related projects the user can just override the ``<<<`` and ``>>>`` typeclass using the smt version.

**Comment by PratherConid** [comment]
Oh, another minor issue here: Line 56
```/-- Return the `i`-th least significant bit. -/``
should be
``/-- Return the `i`-th most significant bit. -/``

**Comment by PratherConid** [comment]
@joehendrix I think the ``rotate_left`` and ``rotate_right`` comment does not need to be changed. The ``rotate_left`` and ``rotate_right`` in SMT-lib uses natural numbers as ``shamt``, but require them to be literals.
Another issue is that the signature and semantics of ``zeroExtend`` does not match SMT-Lib.

**Comment by digama0** [comment]
I think we should have another version of `zeroExtend` with the SMT-lib semantics; that signature will be problematic for lean and I don't want to encourage people to use it unless it is specifically for SMT-lib compatibility.

**Comment by PratherConid** [comment]
> I think we should have another version of `zeroExtend` with the SMT-lib semantics; that signature will be problematic for lean and I don't want to encourage people to use it unless it is specifically for SMT-lib compatibility.

Why is the signature problematic? I saw that ``BitVec.signExtend`` has the same signature as smt-lib. I'm also confused about why we want different signatures for ``zeroExtend`` and ``signExtend``.

**Comment by digama0** [comment]
Actually I think we should also make `signExtend` have the same signature as `zeroExtend`, with it having the same `truncate` behavior when the target size is less than the input size.

The reason the SMT-lib signature is problematic is because it puts an expression in a type dependency, and this will cause unification issues when chaining the function with other functions. For example if you have `UIntN (n : Nat) := BitVec (8 * n)` then you can't use SMT-lib `zeroExtend` to go from `UIntN n` to `UIntN (n + m)` because you need something of type `BitVec (8 * (n + m))` rather than `BitVec (8 * n + 8 * m)`. With the current definition this just works.

**Comment by PratherConid** [comment]
I see. Then we should make ``signExtend`` have the same signature as ``zeroExtend``, and have a smt-lib version for both ``signExtend`` and ``zeroExtend``.

**Comment by joehendrix** [comment]
I agree with @digama0.  I can modify `signExtend` to have the same signature.  In addition to Mario's reason, I also think code is easier to read when the output width is given explicitly, e.g. if `x : BitVec 8` then and I want to extend it to 32-bits, then I prefer writing `signExtend 32 x` rather than `signExtend 24 x`.

@PratherConid What do you want the SMT-LIB version for?   Are you trying to translate SMT-LIB into Lean or the other way around?

**Comment by PratherConid** [comment]
I'm doing the other way around (translating Lean into SMT-LIB), so I need to reliably recognize SMT-LIB primitives from Lean expressions. The translation would be much easier to accomplish if the users use Lean definitions that directly correspond to the SMT-LIB primitive.

**Comment by joehendrix** [comment]
I'm not sure that's realistic to expect users to write Lean code that is so closely aligned with SMT-LIB.  Users will use what is comfortable to them.

One easy thing that you could do would be to write the operators that you want to recognize in your translation procedure, and then use simp rules to map from the `std4` operators to the ones you want to recognize.

**Comment by PratherConid** [comment]
I see. Actually I'm doing that right now.

**Comment by PratherConid** [comment]
I still prefer having them in std4 because in that case I can directly use them in my code. Also, since we already have things like ``smtUDiv, smtSDiv``, it doesn't make sense to not have smt versions for shift and extend.

**Comment by joehendrix** [comment]
@PratherConid To be honest this feels like a very particular hypothetical user here, but maybe you have a particular customer in mind?

I've developed symbolic execution tools for a lot of languages, and they generally don't have bitvector operations that exactly correspond to SMT-LIB.  It can sometimes mean there is a bit of extra simplification or the SMT is slightly more complex than optimal, but that's not where we run into difficulties.  The difficulties are either hard SMT problems or data structures and other language features that have no SMT representation.

Incidentally, since it made the Alive example much more readable, I did commit the instances so that the shift operation can be a bitvector so e.g., `bv <<< 5#n / 3#n` works.  The operator just doesn't have a name.

**Comment by PratherConid** [comment]
@joehendrix No, I didn't have a particular customer in mind. I'm not familiar with verification, so I don't quite understand the difficulties. Thanks for the instance you added!

**Comment by PratherConid** [comment]
> @joehendrix I think the `rotate_left` and `rotate_right` comment does not need to be changed. The `rotate_left` and `rotate_right` in SMT-lib uses natural numbers as `shamt`, but require them to be literals. Another issue is that the signature and semantics of `zeroExtend` does not match SMT-Lib.

I'll repeat my comment here. Note that Mario and I has agreed that the signature of `zeroExtend` should remain unchanged, and the signature of `signExtend` should match `zeroExtend`.
